version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  jcdecaux-producer-kafka:
      container_name: jcdecauxproducerkafka
      build:
        context: JcdecauxProducerKafka
        dockerfile: Dockerfile
      image: jcdecauxproducerkafka:latest
      ports:
        - 8181:8181
      depends_on:
        - kafka
  jcdecaux-consumer-kafka:
    container_name: jcdecauxconsumerkafka
    build:
      context: JcdecauxConsumerKafka
      dockerfile: Dockerfile
    image: jcdecauxconsumerkafka:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka