version: "3"
services:
  zipkin-server:
    container_name: zipkin-server
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - spring-cloud-network
  config-server:
      container_name: config-server
      build:
        context: config-server
        dockerfile: Dockerfile
      image: config-server:latest
      ports:
        - 8101:8101
      networks:
        - spring-cloud-network
  eureka-server:
    container_name: eureka-server
    build:
      context: eureka-server
      dockerfile: Dockerfile
    image: eureka-server:latest
    ports:
      - 8102:8102
    networks:
      - spring-cloud-network
  springcloudgateway-server:
    container_name: springcloudgateway-server
    build:
      context: springcloudgateway-server
      dockerfile: Dockerfile
    image: springcloudgateway-server:latest
    ports:
      - 8004:8004
    depends_on:
      - zipkin-server
    networks:
      - spring-cloud-network
  microservice-produits:
    container_name: microservice-produits
    build:
      context: microservice-produits
      dockerfile: Dockerfile
    image: microservice-produits:latest
    ports:
      - 8001:8001
    depends_on:
      - zipkin-server
    networks:
      - spring-cloud-network
  microservice-commandes:
    container_name: microservice-commandes
    build:
      context: microservice-commandes
      dockerfile: Dockerfile
    image: microservice-commandes:latest
    ports:
      - 8002:8002
    depends_on:
      - zipkin-server
    networks:
      - spring-cloud-network
  microservice-paiement:
    container_name: microservice-paiement
    build:
      context: microservice-paiement
      dockerfile: Dockerfile
    image: microservice-paiement:latest
    ports:
      - 8003:8003
    depends_on:
      - zipkin-server
    networks:
      - spring-cloud-network
  microservice-clientui:
    container_name: microservice-clientui
    build:
      context: clientui
      dockerfile: Dockerfile
    image: microservice-clientui:latest
    ports:
      - 8080:8080
    depends_on:
      - zipkin-server
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge